name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * SUN"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
